image:
  file: .gitpod.Dockerfile

# exposed ports
ports:
- port: 5432 # PostgreSQL
  onOpen: ignore
- port: 8069 # preview on browser
  onOpen: open-browser

tasks:
  - init: |
      echo "Clone repository..."
      git clone --depth 1 --branch 13.0 https://github.com/OCA/OCB odoo13
      echo "Create runnable script..."
      echo "./odoo-bin --addons-path=./addons --db_host 127.0.0.1" > ./odoo13/run.sh
      sudo chmod +x ./odoo13/run.sh
    command: cd odoo13 && ./run.sh
  - command: gp await-port 8069 && gp preview "$(gp url 8069)/web/database/selector"

# P.S. You should remove ":433" from the url when running the web preview.

# Create User
#psql -c "CREATE USER odoo13;"

# Create a database
#psql -c "CREATE DATABASE odoo13_db WITH OWNER odoo13;"
#psql -c "GRANT ALL PRIVILEGES ON DATABASE odoo13_db TO odoo13;"

# Run with database:
#./odoo-bin -w odoo13 -r odoo13 -d odoo13_db --addons-path=./addons --db_host 127.0.0.1

# Run with different PostgreSQL port:
#./odoo-bin -w odoo13 -r odoo13 --addons-path=./addons --db_host 127.0.0.1 --db_port 5433

# Run and init a database:
#./odoo-bin -w odoo13 -r odoo13 -d odoo13_db --addons-path=./addons --db_host 127.0.0.1 -i base
